name = "app"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
DISCORD_CLIENT_ID = '1295493101758189579'
DISCORD_REDIRECT_URI = 'http://app.knighthacks.org/login/discord/callback'

[[d1_databases]]
binding = "DB"
database_name = "blade"
database_id = "ba606b1e-4eba-40ee-90b0-03bef6e21d84"
preview_database_id = "DB"
migrations_dir = "../../packages/db/src/migrations"

[env.preview]
name = "app-preview"

[env.preview.vars]
DISCORD_CLIENT_ID = '1295493101758189579'
DISCORD_REDIRECT_URI = 'http://auth.knighthacks.org/login/discord/callback'

[[env.preview.d1_databases]]
binding = "DB"
database_name = "blade"
database_id = "ba606b1e-4eba-40ee-90b0-03bef6e21d84"
preview_database_id = "DB"
migrations_dir = "../../packages/db/src/migrations"
